### ISSUE TITLE
Create a console program to sync

### ISSUE THREAD

**Issue by adonyssantos** [adonyssantos/git-config-sync#4]
## The idea

Create a console program to perform this process in a simplified way.

### Eg:

**First time (creating the BK)**.
```bash
git-config-sync login --github
git-config-sync set-folder /home/username/
git-config-sync set-repo adonyssantos/git-config-sync
git-config-sync push
```

Maybe `set-folder` and `set-repo` could be summarized in one command. Eg: `git-config-sync set /home/username/ adonyssantos/git-config-sync`.

**Other times (to download the BK)**.
```
git-config-sync login --github
git-config-sync set-folder /home/username/
git-config-sync set-repo adonyssantos/git-config-sync
git-config-sync pull
```

## Roadmap

- [ ] Create a bash script
- [ ] Create an NPM package
- [ ] Create a binary for Linux, Mac, and Windows

**Comment by jcorona48** [comment]
It would be interesting to add a page where you can upload personal configurations and make it like a catalog where any user can copy another user's configuration if it is public.

**Comment by adonyssantos** [comment]
> It would be interesting to add a page where you can upload personal configurations and make it like a catalog where any user can copy another user's configuration if it is public.

That's a good idea, maybe we can do that using Astro and [Palm Tree 2.0](https://github.com/adonyssantos/palm-tree-css-library/issues/25) (A classless CSS open-source library that I'm building).

**Comment by adonyssantos** [comment]
Update: the console program is implemented as the **`dotsync`** CLI and refined in #7.

- `init` / `use` / `link` / `unlink` / `push` / `pull` / `status` / `doctor` / `where`.
- `doctor` replaces the proposed `login --github` by diagnosing git auth and guiding the fix, instead of reimplementing GitHub login.
- One-line install: `curl -fsSL https://raw.githubusercontent.com/adonyssantos/dotsync/main/install.sh | bash`.

The "bash script" roadmap item is done; NPM package and prebuilt binaries are deferred (rationale in the issue body). The catalog idea should move to its own issue.
